version: "3"
services:
  db:
    image: mongo
    volumes:
      - /data/db
  app:
    build: .
    command: "npm start"
    environment:
      NODE_ENV: "production"
      MONGO_PORT: 27017
      MONGO_HOST: db
      MONGO_DB: "myapp"
    image: app
    links:
      - db
    ports:
      - "3000:3000"
